// <auto-generated />
using ABC_FoodCatering.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ABC_FoodCatering.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220811063048_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ABC_FoodCatering.Models.Order", b =>
                {
                    b.Property<int>("orderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("clientName");

                    b.Property<string>("deliveryAddress");

                    b.Property<string>("deliveryDateAndTime");

                    b.Property<string>("foodDes")
                        .IsRequired();

                    b.Property<string>("orderDate");

                    b.Property<int>("quantity");

                    b.HasKey("orderID");

                    b.ToTable("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
